name: Test Devcontainer

on:
  push:
    branches: [ main, sculptor/add-codespaces-devcontainer ]
    paths:
      - '.devcontainer/**'
      - 'Dockerfile'
      - '.dockerignore'
      - 'pyproject.toml'
  pull_request:
    branches: [ main ]
    paths:
      - '.devcontainer/**'
      - 'Dockerfile'
      - '.dockerignore'
      - 'pyproject.toml'

jobs:
  test-devcontainer:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Build and test devcontainer
      uses: devcontainers/ci@v0.3
      with:
        imageName: crossfilter-devcontainer
        runCmd: |
          # Test that Python environment is set up correctly
          python --version
          which python
          
          # Test that uv is available
          uv --version
          
          # Test that dependencies are installed
          uv run python -c "import crossfilter; print('Crossfilter imports successfully')"
          
          # Test that development tools are available
          uv run --extra dev black --version
          uv run --extra dev ruff --version
          uv run --extra dev mypy --version
          uv run --extra dev pytest --version
          
          # Test that Playwright browsers are installed
          uv run --extra dev playwright --version
          
          # Run a quick test to ensure the environment works
          uv run --extra dev python -c "
          import sys
          import crossfilter.main
          print('All basic imports successful')
          print(f'Python version: {sys.version}')
          print('Devcontainer test passed!')
          "
        
        env:
          PYTHONPATH: /workspace